Pin downloader `csv2parquet` dependency specifically to v0.6.0, because versions starting from v0.6.1 choke on Covid19Datos-V2 CSVs:
Error: ArrowError("underlying Arrow error: Parser error: Error while parsing value 2020-03-09 00:00:00 for column 6 at line 2")