Got an out of memory error that asks me to create an on-disk database to spill data to:
```
Error: near line 1: Out of Memory Error: could not allocate block of size 361.9MB (2.9GB/3.2GB used)
Database is launched in in-memory mode and no temporary directory is specified.
Unused blocks cannot be offloaded to disk.
Launch the database with a persistent storage back-end
Or set PRAGMA temp_directory='/path/to/tmp.tmp'
```